from sqlalchemy import (
    Column, Integer, String, Boolean, DECIMAL, DateTime,
    ForeignKey, Text, TIMESTAMP
)
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime
Base = declarative_base()
class Marques(Base):
    __tablename__ = "marques"
    id = Column(Integer, primary_key=True, autoincrement=True)
    nom = Column(String(100))
    alias = Column(String(50))
    is_main = Column(Boolean, default=False)
    is_mdd = Column(Boolean, default=False)
    tauxComission = Column(DECIMAL(10, 2))
    is_visible = Column(Boolean, default=True)
    has_parts = Column(Boolean, default=False)
    is_visible_support = Column(Boolean, default=True)
    isHomeShop = Column(Boolean, default=False)
    color = Column(String(6))
    c0 = Column(String(6))
    c1 = Column(String(6))
    c2 = Column(String(6))
    c3 = Column(String(6))
    c4 = Column(String(6))
    white = Column(Boolean, default=False)
    lien = Column(String(100))
    image = Column(String(100))
    image_redirection = Column(String(150))
    url_redirection = Column(String(150))
    tr_title = Column(Integer, ForeignKey('translate.id'))
    tr_text = Column(Integer, ForeignKey('translate.id'))
    tr_text_2 = Column(Integer, ForeignKey('translate.id'))
    tr_meta_text = Column(Integer, ForeignKey('translate.id'))
    tr_description_b2b = Column(Integer, ForeignKey('translate.id'))
    site = Column(String(20))
    background_site = Column(String(100))
    type = Column(Integer)
    ordre = Column(Integer)
    facebook = Column(String(100))
    twitter = Column(String(100))
    google = Column(String(100))
    youtube = Column(String(100))
    instagram = Column(String(100))
    vine = Column(String(100))
    serie_ean = Column(Integer)
    is_bftg = Column(Boolean, default=False)
    select_market = Column(Boolean, default=False)
    needPieces = Column(Boolean, default=False)
    is_external = Column(Boolean, default=False)
    is_seller = Column(Boolean, default=False)
    genere_nom_produit_auto = Column(Boolean, default=False)
    is_origine = Column(Boolean, default=False)
    is_show_part_brand_search = Column(Boolean, default=False)
    # updated_at = Column(DateTime, default=datetime.utcnow)
    aliases = relationship("MarquesAlias", back_populates="brand")
    env_products = relationship("EnvironmentProduct", back_populates="product")
    title_translation = relationship("Translate", foreign_keys=[tr_title])
    text_translation = relationship("Translate", foreign_keys=[tr_text])
    text_2_translation = relationship("Translate", foreign_keys=[tr_text_2])
    meta_translation = relationship("Translate", foreign_keys=[tr_meta_text])
    desc_b2b_translation = relationship("Translate", foreign_keys=[tr_description_b2b])
class MarquesAlias(Base):
    __tablename__ = "marques_alias"
    brand_id = Column(Integer, ForeignKey("marques.id"), primary_key=True)
    alias = Column(String(64), primary_key=True)
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    # updated_at = Column(TIMESTAMP, default=datetime.utcnow, onupdate=datetime.utcnow)
    brand = relationship("Marques", back_populates="aliases")
class EnvironmentProduct(Base):
    __tablename__ = "environment_product"
    environment_id = Column(Integer, primary_key=True)
    product_id = Column(Integer, ForeignKey("marques.id"), primary_key=True)
    product = relationship("Marques", back_populates="env_products")
class Translate(Base):
    __tablename__ = "translate"
    id = Column(Integer, primary_key=True, autoincrement=True)
    fr = Column(Text)
    en = Column(Text)
    es = Column(Text)
    po = Column(Text)
    de = Column(Text)
    gr = Column(Text)
    cn = Column(Text)
    ru = Column(Text)
    ne = Column(Text)
    it = Column(Text)
    pl = Column(Text)
    hu = Column(Text)
    sk = Column(Text)
    cs = Column(Text)
    hr = Column(Text)
    ro = Column(Text)
    bg = Column(Text)
    id_type = Column(Integer)
    table = Column(String(50))
    field = Column(String(50))
    target = Column(Integer)
    status = Column(String)